### ISSUE TITLE
balancing issue

### ISSUE THREAD

**Issue by dotbot123** [c-rxxp-y/n-gon-enhanced#3]
mass-energy ratio + additive manufacturing or working  mass is super op and you can heal whenever you want (maybe make them exclusive to each other)

also, make it so that with mass-energy ratio it depends on the charging of the throw so you cant just spam it

**Comment by c-rxxp-y** [comment]
thanks for the input, I'll look at this later

**Comment by c-rxxp-y** [comment]
I'll change mass-energy ratio to only be available for some fields (and turn it into a field tech) and also make the heal orb based on throw charge level

**Comment by dotbot123** [comment]
ok :) thanks
