### ISSUE TITLE
building mode

### ISSUE THREAD

**Issue by dotbot123** [c-rxxp-y/n-gon-enhanced#4]
no erase feature
nothing other than blocks and platforms, no lasers, no buttons, no elevators
cant get tech "building tools"
no downloading or uploading levels

**Comment by c-rxxp-y** [comment]
1. press z to undo
2. making stuff other than blocks/platforms requires you to add them in the levels code (working on adding them in the game)
3. I'll check on that
4. press Ctrl+A then Ctrl+C to copy the level code while in the game (the white box in the bottom right corner of the screen has the code in it)

**Comment by dotbot123** [comment]
ok

**Comment by dotbot123** [comment]
![image](https://github.com/user-attachments/assets/30b720cc-b402-4b85-a41a-5b417129175c)

**Comment by c-rxxp-y** [comment]
fixed the lack of builder tools in experiment, and also removed it from a normal run
